SUPPORTED_MODELS = {
    "DF": {
        "file": "DF.py",
        "class_name": "DF",
        "feature": "DIR",
        "seq_len": 5000,
        "train_epochs": 30,
        "train_batch_size": 128,
        "eval_batch_size": 256,
        "learning_rate": 2e-3,
        "optimizer": "Adamax",
        "loss": "CrossEntropyLoss",
        "save_metric": "macro_f1",
        "derived_feature": None,
        "default_enabled": True,
    },
    "AWF": {
        "file": "AWF.py",
        "class_name": "AWF",
        "feature": "DIR",
        "seq_len": 3000,
        "train_epochs": 30,
        "train_batch_size": 256,
        "eval_batch_size": 256,
        "learning_rate": 8e-4,
        "optimizer": "RMSprop",
        "loss": "CrossEntropyLoss",
        "save_metric": "macro_f1",
        "derived_feature": None,
        "default_enabled": True,
    },
    "TikTok": {
        "file": "TikTok.py",
        "class_name": "TikTok",
        "feature": "DT",
        "seq_len": 5000,
        "train_epochs": 30,
        "train_batch_size": 128,
        "eval_batch_size": 256,
        "learning_rate": 2e-3,
        "optimizer": "Adamax",
        "loss": "CrossEntropyLoss",
        "save_metric": "macro_f1",
        "derived_feature": None,
        "default_enabled": True,
    },
    "VarCNN": {
        "file": "VarCNN.py",
        "class_name": "VarCNN",
        "feature": "DT2",
        "seq_len": 5000,
        "train_epochs": 30,
        "train_batch_size": 50,
        "eval_batch_size": 256,
        "learning_rate": 1e-3,
        "optimizer": "Adam",
        "loss": "CrossEntropyLoss",
        "save_metric": "macro_f1",
        "derived_feature": None,
        "default_enabled": True,
    },
    "BAPM": {
        "file": "BAPM.py",
        "class_name": "BAPM",
        "feature": "DIR",
        "seq_len": 8500,
        "train_epochs": 30,
        "train_batch_size": 128,
        "eval_batch_size": 256,
        "learning_rate": 5e-4,
        "optimizer": "Adam",
        "loss": "CrossEntropyLoss",
        "save_metric": "macro_f1",
        "num_tabs_arg": True,
        "derived_feature": None,
        "default_enabled": True,
    },
    "TMWF": {
        "file": "TMWF.py",
        "class_name": "TMWF",
        "feature": "DIR",
        "seq_len": 30720,
        "train_epochs": 30,
        "train_batch_size": 80,
        "eval_batch_size": 256,
        "learning_rate": 5e-4,
        "optimizer": "Adam",
        "loss": "CrossEntropyLoss",
        "save_metric": "macro_f1",
        "num_tabs_arg": True,
        "derived_feature": None,
        "default_enabled": True,
    },
    "RF": {
        "file": "RF.py",
        "class_name": "RF",
        "feature": "TAM",
        "base_seq_len": 5000,
        "seq_len": 1800,
        "train_epochs": 30,
        "train_batch_size": 200,
        "eval_batch_size": 256,
        "learning_rate": 5e-4,
        "optimizer": "Adam",
        "loss": "CrossEntropyLoss",
        "save_metric": "macro_f1",
        "derived_feature": "TAM",
        "default_enabled": True,
    },
    "ARES": {
        "file": "ARES.py",
        "class_name": "ARES",
        "feature": "MTAF",
        "base_seq_len": 10000,
        "seq_len": 8000,
        "train_epochs": 30,
        "train_batch_size": 512,
        "eval_batch_size": 512,
        "learning_rate": 2e-3,
        "optimizer": "AdamW",
        "loss": "CrossEntropyLoss",
        "save_metric": "macro_f1",
        "lradj": "StepLR",
        "derived_feature": "MTAF",
        "default_enabled": True,
    },
    "TF": {
        "file": "TF.py",
        "class_name": "TF",
        "feature": "DIR",
        "seq_len": 5000,
        "loss": "TripletMarginLoss",
        "eval_method": "kNN",
        "default_enabled": False,
        "status": "special_flow_not_enabled_by_default",
    },
    "NetCLR": {
        "file": "NetCLR.py",
        "class_name": "NetCLR",
        "feature": "DIR",
        "seq_len": 5000,
        "default_enabled": False,
        "status": "requires_pretraining_policy",
    },
    "Holmes": {
        "file": "Holmes.py",
        "class_name": "Holmes",
        "feature": "TAF",
        "seq_len": 2000,
        "default_enabled": False,
        "status": "requires_attribution_augmentation_and_spatial_analysis",
    },
}


def default_models():
    return [name for name, cfg in SUPPORTED_MODELS.items() if cfg.get("default_enabled")]


def model_config(model_name):
    if model_name not in SUPPORTED_MODELS:
        raise KeyError(f"Unsupported model {model_name}. Available: {sorted(SUPPORTED_MODELS)}")
    return dict(SUPPORTED_MODELS[model_name])
